//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haber
    {
        public int ID { get; set; }
        public string HaberBasligi { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public string HaberIcerigi { get; set; }
        public byte[] HaberFoto { get; set; }
        public string ResimYolu { get; set; }
    }
}
